---
title: "Summary"
author: "Evan Odell"
date: Sys.Date()
output: html_document
bibliography: ExportedItems.bib
---

# Disability discussion in parliament
How do politicians discuss disability issues? Has this changed over time? Are there any relationships between how disability issues are debated in Parliament and the policy decisions made by governments? In an attempt to answer these questions I downloaded everything that has ever been said in the House of Commons from 1936 to the present day.

#### Data set
The ParlParse service, operated by Theyworkforyou.co.uk, records everything said in parliament from 1936 to the present day, allowing for 80 years of parliamentary debate and discussion to be analysed. The dataset includes 4,979,806 different speeches, of which 438,180 are included in this analysis, as they contain one or more of the disability phrases searched for.

## Frequency of mentions of disability-relevant phrases

I grouped 23 different disability relevant phrases into 15 groups. I selected phrases that are likely to be only used in relation to disability issues. This means that words such as 'blind' or 'deaf' cannot be used, as they are frequently used in non-disability discussion; e.g. 'the member opposite is deaf to the concerns of ordinary people'. The number of each group of phrases were counted for each day of debate in parliament, and averaged over the year.

## Sentiment analysis

In addition to the frequency of different words used in the Hansard, I wanted to see if there are any changes in the sentiment of disability discussion. There are three options for sentiment analysis:

1. The [http://www2.imm.dtu.dk/pubdb/views/publication_details.php?id=6010](AFINN) library by Finn Årup Nielsen, labelled 'AFINN'. AFINN assigns a score from -5 (most negative) to +5 (most positive) to the words used in association with the different disability terms and phrases searched for in the Hansard.

2. The [https://www.cs.uic.edu/~liub/FBS/sentiment-analysis.html](Opinion Mining, Sentiment Analysis), and Opinion Spam Detection</a> dataset by Bing Liu, Minqing Hu and Junsheng Cheng, labelled 'Bing'. Bing identifies a word as either positive or negative.

3. The [http://saifmohammad.com/WebPages/lexicons.html](NRC Word-Emotion Association Lexicon), library by Saif M. Mohammad, labelled 'NRC'. NRC assigns one of positive, negative, anger, anticipation, disgust, fear, joy, sadness, surprise and trust.

The sentiment analysis tab has three different charts you can toggle between. The default chart is a line chart showing a smoothed line of the average score trend over time. The second is a bar chart showing the average sentiment score each year, and the third is a box plot showing the distribution of sentiment scores in each year.

The orange 'All Debate' group is the sentiment score for a random sample of 4% of all debate in Parliament, and the blue 'Disability' group is the sentiment score for all debates that involve any of the disability-relevant terms and phrases.

The sentiment of all debates was, throughout the 1930s and 1940s, predominantly negative, on average. 1983 was the last year that disability debate was, on aggregate, negative, and 1994 was the first year where the sentiment in debate on disability issues was more positive than the average sentiment of parliamentary debate, and disability sentiment was also more positive than average every year from 1997 to 2010. Since 2011 disability sentiment has been less positive than overall debate sentiment, but the degree of positivity has increased year on year since 2013.



#### Phrases Used


* Disability Other
  + 'disability'

* Disabled People
  + 'disabled person'
  + 'disabled people'

* Disabled Children
  + 'disabled child

* People with Disability
  + 'person with a disability'
  + 'people with a disability'
  + 'people with disabilities'
  + 'person with disabilities'

* Any with Disability
  + 'with a disability'
  + 'with disabilities'

* Disabled Men
  + 'disabled men'

* Disabled Men
  + 'disabled women'

* Children with Disability
  + 'child with a disability'
  + 'children with a disability'
  + 'children with disabilities'
  + 'child with disabilities'

* Independent Living
  + 'independent living'

* Wheelchair
  + 'wheelchair'

* Paralympic
  + 'paralympic'

* Spastic
  + 'spastic'

* Sub-Normal
  + 'sub_normal'

* Amputee
  + 'amputee'

* Retard
  + 'retard'



## References

Nielsen, Finn Årup. 2011. *AFINN*. Lyngby, Denmark: Informatics and Mathematical Modelling, Technical University of Denmark.


### Notes

Source code is available on [Github](https://github.com/EvanOdell/hansardBlog). For assistance, questions or comments please contact Evan Odell via [email](mailto:evan.odell@disabilityrightsuk.org) or  [Twitter](https://twitter.com/evanodell), or raise an issue on Github.

This app is licensed under an [MIT License](https://github.com/EvanOdell/hansardBlog/blob/master/LICENSE).

The data used in this app was retrieved from the [ParlParse](https://www.theyworkforyou.com/pwdata/scrapedxml/) service operated by [MySociety](https://www.mysociety.org/).

This app was constructed using [`shiny`](http://shiny.rstudio.com/) and `shinydashboard`, with plots produced with `ggplot2` and `scales`. Access to the sentiment analysis libraries was through the `tidytext` package.
